[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Chi2AD User's Guide"
authors = [{name = "Camilo Nunez-Fernandez", email = "camilo.nunezf@sansano.usm.cl"}]
dynamic = ["0.1.0", "Docs for usage of Chi2AD"]
